
# Dockerfile.nginx
FROM nginx:latest

# Copia il file di configurazione nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf

# Copia il build di Angular dal contesto di build
#COPY ../front-end-app/dist/front-end-app /usr/share/nginx/html

# Esponi la porta 80 (Nginx di default usa la porta 80)
EXPOSE 80